---
title: "Big5Moderators_Lonely_centered_pooled"
output: html_document
date: '2022-09-13'
---


---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(sjPlot)
library(interactions)
library(jtools)
main_effect_updated<-read_csv("/Volumes/GoogleDrive/My Drive/Social media Sensitivity Pooled Analyses/Data Prep/modelling_data_pooled.csv")
```

```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert,
                lonely_r, 
                demog_age.z,
                MediaUse.scaled, MediaUse.mean,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz) %>%
  na.omit() %>% distinct()

baseline_personality_sm<-lmer(lonely_r ~ 1 +
                                demog_sex_recoded+ 
                                demog_age.z+
                                surveys_per_id.z+
                                overall_study_day+
                                weekend+
                                nAct.cz+
                                lagDur.cz*laggedLonely.cz+
                                MediaUse.scaled+MediaUse.mean+
                                (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                              REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(baseline_personality_sm)

mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, 
                lonely_r, 
                demog_age.z,
                socialmedia.cz, socialmedia.bp.z,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz) %>%
  na.omit() %>% dplyr::distinct()

baseline_personality_duration<-lmer(lonely_r~ 1 +
                                      demog_sex_recoded+ 
                                      demog_age.z+
                                      surveys_per_id.z+
                                      overall_study_day+
                                      weekend+
                                      nAct.cz+
                                      lagDur.cz*laggedLonely.cz+
                                      socialmedia.cz+socialmedia.bp.z+
                                      (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                                    REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(baseline_personality_duration)
```


```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, 
                lonely_r, 
                demog_age.z,
                MediaUse.scaled, MediaUse.mean,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz,
                extraversion.z) %>%
  na.omit() %>% dplyr::distinct()


extraversion_sm<-lmer(lonely_r ~ 1 +
                        demog_sex_recoded+ 
                        demog_age.z+
                        surveys_per_id.z+
                        overall_study_day+
                        weekend+
                        nAct.cz+
                        lagDur.cz*laggedLonely.cz+
                        MediaUse.mean*extraversion.z+MediaUse.scaled*extraversion.z+
                        (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                      REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(extraversion_sm)

mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, 
                lonely_r, 
                demog_age.z,
                socialmedia.cz, socialmedia.bp.z,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz,
                extraversion.z) %>%
  na.omit() %>% dplyr::distinct()

extraversion_duration<-lmer(lonely_r ~ 1 +
                              demog_sex_recoded+ 
                              demog_age.z+
                              surveys_per_id.z+
                              overall_study_day+
                              weekend+
                              nAct.cz+
                              lagDur.cz*laggedLonely.cz+
                              socialmedia.bp.z*extraversion.z+socialmedia.cz*extraversion.z+
                              (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                            REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(extraversion_duration)
```


```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, 
                lonely_r, 
                demog_age.z,
                MediaUse.scaled, MediaUse.mean,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz,
                openness.z) %>%
  na.omit() %>% dplyr::distinct()

openness_sm<-lmer(lonely_r ~ 1 +
                    demog_sex_recoded+ 
                    demog_age.z+
                    surveys_per_id.z+
                    overall_study_day+
                    weekend+
                    nAct.cz+
                    lagDur.cz*laggedLonely.cz+
                    MediaUse.mean*openness.z+MediaUse.scaled*openness.z+
                    (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                  REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(openness_sm)


mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, 
                lonely_r, 
                demog_age.z,
                socialmedia.cz, socialmedia.bp.z,
                demog_sex_recoded,
                weekend, 
                nAct.cz,
                surveys_per_id.z,
                lagDur.cz,
                overall_study_day,
                laggedLonely.cz,
                openness.z) %>%
  na.omit() %>% dplyr::distinct()

openness_duration<-lmer(lonely_r ~ 1 +
                          demog_sex_recoded+ 
                          demog_age.z+
                          surveys_per_id.z+
                          overall_study_day+
                          weekend+
                          nAct.cz+
                          lagDur.cz*laggedLonely.cz+
                          socialmedia.bp.z*openness.z+socialmedia.cz*openness.z+
                          (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                        REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(openness_duration)
```


```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, neuroticism.z) %>%
  na.omit() %>% dplyr::distinct() %>%
  distinct()


neuroticism_sm<-lmer(lonely_r ~ 1 +
                       demog_sex_recoded+ 
                       demog_age.z+
                       surveys_per_id.z+
                       overall_study_day+
                       weekend+
                       nAct.cz+
                       lagDur.cz*laggedLonely.cz+
                       MediaUse.mean*neuroticism.z+MediaUse.scaled*neuroticism.z+
                       (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                     REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(neuroticism_sm)

int<-sim_slopes(neuroticism_sm, pred=MediaUse.scaled, modx=neuroticism.z, jnplot = TRUE)
plot<-interact_plot(neuroticism_sm, pred=MediaUse.scaled, modx=neuroticism.z, interval=TRUE) +xlab("Social Media Use (WP)") +ylab("Lonely (R)")+theme_apa()+ggtitle("Neuroticism Trait")
plot
ggsave("Interact: Neuroticism Moderator - Use.png")
jnplot<-int$jnplot +xlab("Neuroticism") + ylab("Slope of Social Media Use and Lonely") + ggtitle("JN Plot")
ggsave("Neuroticism Moderator - Use - JN Plot.png")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="High Neuroticism", `- 1 SD`="Low Neuroticism")
s<-ggplot(data=probe, aes(x=MediaUse.scaled, y=lonely_r, group=trial, colour=trial, fill=trial))+geom_line(size=1.5)+geom_ribbon(aes(ymin = ymin, ymax = ymax, group=trial, fill=trial), alpha=0.3)+xlab("Use vs Non-Use") + ylab("Loneliness") + coord_cartesian(
  ylim = c(3.15, 4),
  expand = TRUE,
  default = FALSE)+ scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Non-Use", "Use")) +
  theme_apa()+theme(axis.text = element_text(size = 30)) + scale_color_manual(values=c("#F98400", "#5BBCD6")) + scale_fill_manual(values=c("#F98400", "#5BBCD6"))+ theme(axis.text = element_text(size = 30), axis.title.x = element_text(size=30), axis.title.y=element_text(size=30), legend.text = element_text(size=30), legend.position = c(.98, .98), legend.justification = c("right", "top"),legend.box.just = "right", legend.margin = margin(6, 6, 6, 6))

ggsave("LinePlot: Neuroticism Moderators (BP) of Social Media Use (WP) x Lonely.pdf", width=10, height=10)


probe2<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD") %>%
  dplyr::mutate(
    socialmedia=case_when(
    MediaUse.scaled<0 ~ "Before",
    MediaUse.scaled>0 ~ "After"
  ), context=case_when(
    modx_group=="+ 1 SD" ~ "High 
  Neuroticism",
    modx_group== "- 1 SD" ~ "Low
  Neuroticism"
  )) %>%
  dplyr::group_by(context, socialmedia) %>%
  dplyr::summarise(
    wb=mean(lonely_r, na.rm=TRUE)) %>%
  arrange(desc(socialmedia))

probe2$socialmedia<-factor(probe2$socialmedia, levels=c("After", "Before"))
probe2$socialmedia<-fct_reorder(probe2$socialmedia, desc(probe2$socialmedia))

s<-ggplot(data=probe2, aes(x=context, y=wb, group=socialmedia, fill=socialmedia))+
  geom_col(width=0.5, position=position_dodge(), color="black")+theme_apa() + 
  scale_fill_manual(values=c('darkgrey','white')) + ylab(" ") + xlab(" ") + theme(axis.text = element_text(size = 20))  +  geom_errorbar(aes(ymin=wb-sd(wb, na.rm=TRUE), ymax=wb+sd(wb, na.rm=TRUE)), width=.2, position=position_dodge(.5)) + coord_cartesian(
    ylim = c(2.5,4),
    expand = TRUE,
    default = FALSE)
ggsave("Neuroticism Moderators (WP) - Bar Plot.pdf", height=8, width=8)

```

```{r}

mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, neuroticism.z) %>%
  na.omit() %>% dplyr::distinct()

neuroticism_duration<-lmer(lonely_r ~ 1 +
                             demog_sex_recoded+ 
                             demog_age.z+
                             surveys_per_id.z+
                             overall_study_day+
                             weekend+
                             nAct.cz+
                             lagDur.cz*laggedLonely.cz+
                             socialmedia.bp.z*neuroticism.z+socialmedia.cz*neuroticism.z+
                             (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                           REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(neuroticism_duration)
```

```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, agreeableness.z) %>%
  na.omit() %>% dplyr::distinct()

agreeableness_sm<-lmer(lonely_r ~ 1 +
                         demog_sex_recoded+ 
                         demog_age.z+
                         surveys_per_id.z+
                         overall_study_day+
                         weekend+
                         nAct.cz+
                         lagDur.cz*laggedLonely.cz+
                         MediaUse.mean*agreeableness.z+MediaUse.scaled*agreeableness.z+
                         (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                       REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(agreeableness_sm)

mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, agreeableness.z) %>%
  na.omit() %>% dplyr::distinct()

agreeableness_duration<-lmer(lonely_r ~ 1 +
                               demog_sex_recoded+ 
                               demog_age.z+
                               surveys_per_id.z+
                               overall_study_day+
                               weekend+
                               nAct.cz+
                               lagDur.cz*laggedLonely.cz+
                               socialmedia.bp.z*agreeableness.z+socialmedia.cz*agreeableness.z+
                               (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                             REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(agreeableness_duration)
```

```{r}
mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, conscientiousness.z) %>%
  na.omit() %>% dplyr::distinct()

conscientiousness_sm<-lmer(lonely_r ~ 1 +
                             demog_sex_recoded+ 
                             demog_age.z+
                             surveys_per_id.z+
                             overall_study_day+
                             weekend+
                             nAct.cz+
                             lagDur.cz*laggedLonely.cz+
                             MediaUse.mean*conscientiousness.z+MediaUse.scaled*conscientiousness.z+
                             (1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffectPersonality,
                           REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(conscientiousness_sm)

mainEffectPersonality<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, conscientiousness.z) %>%
  na.omit() %>% dplyr::distinct()

conscientiousness_duration<-lmer(lonely_r ~ 1 +
                                   demog_sex_recoded+ 
                                   demog_age.z+
                                   surveys_per_id.z+
                                   overall_study_day+
                                   weekend+
                                   nAct.cz+
                                   lagDur.cz*laggedLonely.cz+
                                   socialmedia.bp.z*conscientiousness.z+socialmedia.cz*conscientiousness.z+
                                   (1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffectPersonality,
                                 REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(conscientiousness_duration)
```


```{r}
predLabels=c("Intercept",
             "Sex", 
             "Age",
             "Surveys Per Participant",
             "Study Day", 
             "Weekend", 
             "Number of Activites", 
             "Duration Since Last EMA", 
             "Loneliness (R)  at t-1", 
             "Social Media Use (vs Non-Use) (WP)", 
             "Social Media Use (vs Non-Use) (BP)",
             "Duration Since Last EMA x Loneliness (R)   at t-1",
             "Extraversion", 
             "Social Media Use (vs Non-Use) (BP) x Extraversion (BP)",
             "Social Media Use (vs Non-Use) (WP) x Extraversion (BP)", 
             "Openness",
             "Social Media Use (vs Non-Use) (BP) x Openness (BP)",
             "Social Media Use (vs Non-Use) (WP) x Openness (BP)",
             "Agreeableness",
             "Social Media Use (vs Non-Use) (BP) x Agreeableness (BP)",
             "Social Media Use (vs Non-Use) (WP) x Agreeableness (BP)", 
             "Neuroticism",
             "Social Media Use (vs Non-Use) (BP) x Neuroticism (BP)",
             "Social Media Use (vs Non-Use) (WP) x Neuroticism (BP)",
             "Conscientiousness",
             "Social Media Use (vs Non-Use) (BP) x Conscientiousness (BP)",
             "Social Media Use (vs Non-Use) (WP) x Conscientiousness (BP)")

dvLabels=c("Baseline Model",
           "Extraversion Moderator",
           "Openness Moderator",
           "Agreeableness Moderator",
           "Neuroticism Moderator",
           "Conscientiousness Moderator")


tab_model(baseline_personality_sm, 
          extraversion_sm,
          openness_sm,
          agreeableness_sm, 
          neuroticism_sm, 
          conscientiousness_sm,
          pred.labels = predLabels,
          dv.labels = dvLabels,
          file="UseVsNoUse_BigFive_Loneliness (R) .html")

predLabels=c("Intercept",
             "Sex", 
             "Age",
             "Surveys Per Participant",
             "Study Day", 
             "Weekend", 
             "Number of Activites", 
             "Duration Since Last EMA", 
             "Loneliness (R)  at t-1", 
             "Social Media Use Duration (WP)", 
             "Social Media Use Duration (BP)",
             "Duration Since Last EMA x Loneliness (R)  at t-1",
             "Extraversion", 
             "Social Media Use Duration (BP) x Extraversion (BP)",
             "Social Media Use Duration (WP) x Extraversion (BP)", 
             "Openness",
             "Social Media Use Duration (BP) x Openness (BP)",
             "Social Media Use Duration (WP) x Openness (BP)",
             "Agreeableness",
             "Social Media Use Duration (BP) x Agreeableness (BP)",
             "Social Media Use Duration (WP) x Agreeableness (BP)", 
             "Neuroticism",
             "Social Media Use Duration (BP) x Neuroticism (BP)",
             "Social Media Use Duration (WP) x Neuroticism (BP)",
             "Conscientiousness",
             "Social Media Use Duration (BP) x Conscientiousness (BP)",
             "Social Media Use Duration (WP) x Conscientiousness (BP)")


dvLabels=c("Baseline Model",
           "Extraversion Moderator",
           "Openness Moderator",
           "Agreeableness Moderator",
           "Neuroticism Moderator",
           "Conscientiousness Moderator")

tab_model(baseline_personality_duration, 
          extraversion_duration,
          openness_duration,
          agreeableness_duration, 
          neuroticism_duration, 
          conscientiousness_duration,
          pred.labels = predLabels,
          dv.labels = dvLabels,
          file="Duration_BigFive_Loneliness (R) .html")
```


