---
title: "R Notebook"
output: html_notebook
---

```{r}
#### Read in Weekly App Use Files
library(tidyverse)
library(lme4)
library(lubridate)
library(sjPlot)
library(brms)

setwd("~/Desktop/OneDrive - Stanford/CoCo - Social Media Use and Psychological Wellbeing/IdiographicWellbeing/DigitalMediaEffects/Final Weekly Results/Step 2 - Weekly Data Prep")

data<-read_csv("05_appusage_survey_coco_ut1.csv")
demogPers<-read_csv("DemogPersFall.csv")
presurvey<-read_csv("01_presurvey_coco_ut1.csv")
personality<-read_csv("bfi_corrected.csv")
ema_long<-read.csv("04_ema_survey_coco_ut1.csv")
```


#### Step 1: Prep EMA data by aggregating wellbeing states and context-level data at the weekly level

```{r}
final<-ema_long%>%
  dplyr::select(id, StartDateConvert, momentary_wellbeing_happy_ema, momentary_wellbeing_angry_ema, momentary_wellbeing_worried_ema, momentary_wellbeing_sad_ema, momentary_wellbeing_sad_ema, momentary_wellbeing_stressed_ema, momentary_wellbeing_lonely_ema, momentary_wellbeing_accepted_ema, momentary_context_activity_ema, momentary_context_interaction_ema,momentary_context_place_ema, momentary_context_people_ema, momentary_context_social_media_ema)


final$date<-ymd_hms(final$StartDateConvert)
final$date<-format(final$date, format="%Y-%m-%d")


final$Date<-as.Date(final$StartDate)
filtered<-filter(final, final$Date > "2020-10-25" & final$Date < "2020-11-19" )

filtered<- filtered  %>%
  dplyr::mutate(week = case_when(
    Date == "2020-10-25" |  Date > "2020-10-25" & Date <"2020-10-31" | Date =="2020-10-31"  ~ "Week 1",
    Date == "2020-11-01" | Date > "2020-11-01" & Date <"2020-11-07" | Date == "2020-11-07" ~ "Week 2",
    Date == "2020-11-08" |  Date > "2020-11-08" & Date <"2020-11-14" | Date == "2020-11-14" ~ "Week 3",
    Date >"2020-11-15" | Date == "2020-11-15" & Date <"2020-11-19" | Date == "2020-11-19" ~ "Week 4"))


smSubjective<-filtered %>%
  dplyr::group_by(id, date) %>%
  dplyr::mutate(avgDaily=mean(momentary_context_social_media_ema, na.rm=TRUE)) %>%
  dplyr::ungroup () %>%
  dplyr::group_by(id, week) %>%
  dplyr::mutate(avgDailyWeekly=mean(avgDaily, na.rm=TRUE)) %>%
  dplyr::select(id, week, avgDailyWeekly) %>%
  distinct()

filtered<-filtered %>%
  dplyr::rename(angry=momentary_wellbeing_angry_ema,  ## Renaming variables here for ease of use later
                worried=momentary_wellbeing_worried_ema,
                happy=momentary_wellbeing_happy_ema, 
                sad=momentary_wellbeing_sad_ema,
                stressed=momentary_wellbeing_stressed_ema,
                lonely=momentary_wellbeing_lonely_ema,
                accepted=momentary_wellbeing_accepted_ema,
                socialmedia=momentary_context_social_media_ema,
                place=momentary_context_place_ema,
                people=momentary_context_people_ema,
                activity=momentary_context_activity_ema)

### Coding Context Variables 

filtered$closeTies4<-0
filtered$closeTies4<-ifelse(grepl("^4,",filtered$people), 1, filtered$closeTies4)
filtered$closeTies4<-ifelse(grepl(",4,",filtered$people),1, filtered$closeTies4)
filtered$closeTies4<-ifelse(grepl(",4$",filtered$people),1, filtered$closeTies4)
filtered$closeTies4<-ifelse(grepl("^4$",filtered$people),1, filtered$closeTies4)
filtered$closeTies2<-0
filtered$closeTies2<-ifelse(grepl("^5,",filtered$people), 1, filtered$closeTies2)
filtered$closeTies2<-ifelse(grepl(",5,",filtered$people),1, filtered$closeTies2)
filtered$closeTies2<-ifelse(grepl(",5$",filtered$people),1, filtered$closeTies2)
filtered$closeTies2<-ifelse(grepl("^5$",filtered$people),1,filtered$closeTies2)
filtered$closeTies3<-0
filtered$closeTies3<-ifelse(grepl("^6,",filtered$people), 1, filtered$closeTies3)
filtered$closeTies3<-ifelse(grepl(",6,",filtered$people),1, filtered$closeTies3)
filtered$closeTies3<-ifelse(grepl(",6$",filtered$people),1, filtered$closeTies3)
filtered$closeTies3<-ifelse(grepl("^6$",filtered$people),1, filtered$closeTies3)

filtered$closeTies<-ifelse(filtered$closeTies4==1 | filtered$closeTies2==1 | filtered$closeTies3==1, 1, 0)

filtered$closeTies<-ifelse(is.na(filtered$people),as.numeric(NA), filtered$closeTies)

i<-filtered %>%
  select(closeTies, id, people)
### Distant Ties Vs Others
filtered$distantTies4<-0
filtered$distantTies4<-ifelse(grepl("^1,",filtered$people), 1, filtered$distantTies4)
filtered$distantTies4<-ifelse(grepl(",1,",filtered$people),1, filtered$distantTies4)
filtered$distantTies4<-ifelse(grepl(",1$",filtered$people),1, filtered$distantTies4)
filtered$distantTies4<-ifelse(grepl("^1$",filtered$people),1, filtered$distantTies4)
filtered$distantTies2<-0
filtered$distantTies2<-ifelse(grepl("^2,",filtered$people), 1, filtered$distantTies2)
filtered$distantTies2<-ifelse(grepl(",2,",filtered$people),1, filtered$distantTies2)
filtered$distantTies2<-ifelse(grepl(",2$",filtered$people),1, filtered$distantTies2)
filtered$distantTies2<-ifelse(grepl("^2$",filtered$people),1,filtered$distantTies2)
filtered$distantTies3<-0
filtered$distantTies3<-ifelse(grepl("^7,",filtered$people), 1, filtered$distantTies3)
filtered$distantTies3<-ifelse(grepl(",7,",filtered$people),1, filtered$distantTies3)
filtered$distantTies3<-ifelse(grepl(",7$",filtered$people),1, filtered$distantTies3)
filtered$distantTies3<-ifelse(grepl("^7$",filtered$people),1, filtered$distantTies3)

filtered$distantTies<-ifelse(filtered$distantTies4==1 | filtered$distantTies2==1 | filtered$distantTies3==1, 1, 0)

filtered$distantTies<-ifelse(is.na(filtered$people),as.numeric(NA), filtered$distantTies)

i<-filtered %>%
  select(distantTies, id, people)

### Family vs Others

filtered$familyTies4<-0
filtered$familyTies4<-ifelse(grepl("^3,",filtered$people), 1, filtered$familyTies4)
filtered$familyTies4<-ifelse(grepl(",3,",filtered$people),1, filtered$familyTies4)
filtered$familyTies4<-ifelse(grepl(",3$",filtered$people),1, filtered$familyTies4)
filtered$familyTies4<-ifelse(grepl("^3$",filtered$people),1, filtered$familyTies4)

filtered$familyTies<-filtered$familyTies4

filtered$familyTies<-ifelse(is.na(filtered$people),as.numeric(NA), filtered$familyTies)

i<-filtered %>%
  select(familyTies, id, people)

### Alone Vs Others 

### Alone 

filtered$alone4<-0
filtered$alone4<-ifelse(grepl("^8,",filtered$people), 1, filtered$alone4)
filtered$alone4<-ifelse(grepl(",8,",filtered$people),1, filtered$alone4)
filtered$alone4<-ifelse(grepl(",8$",filtered$people),1, filtered$alone4)
filtered$alone4<-ifelse(grepl("^8$",filtered$people),1, filtered$alone4)

filtered$alone<-filtered$alone4
filtered$alone<-ifelse(is.na(filtered$people),as.numeric(NA), filtered$alone)

i<-filtered %>%
  select(alone, id, people)


#### CODING PHYSICAL CONTEXT

### 1 (Bar, party); 2 (Cafe, restaurant); 3 (Friend’s house); 4 (University campus); 5 (Fraternity, sorority house); 6 (Gym); 7 (Home); 8 (Library); 9 (Religious facility); 10 (Store, mall); 11 (Work place (not your home office)); 12 (Vehicle); 13 (Outdoors, park, or in nature); 14 (None of the above, other);

### Study Locations Vs Other Locations 

filtered$home_study4<-0
filtered$home_study4<-ifelse(grepl("^4,",filtered$place), 1, filtered$home_study4)
filtered$home_study4<-ifelse(grepl(",4,",filtered$place),1, filtered$home_study4)
filtered$home_study4<-ifelse(grepl(",4$",filtered$place),1, filtered$home_study4)
filtered$home_study4<-ifelse(grepl("^4$",filtered$place),1, filtered$home_study4)

filtered$home_study2<-0
filtered$home_study2<-ifelse(grepl("^8,",filtered$place), 1, filtered$home_study2)
filtered$home_study2<-ifelse(grepl(",8,",filtered$place),1, filtered$home_study2)
filtered$home_study2<-ifelse(grepl(",8$",filtered$place),1, filtered$home_study2)
filtered$home_study2<-ifelse(grepl("^8$",filtered$place),1,filtered$home_study2)

filtered$home_study<-ifelse(filtered$home_study4==1 | filtered$home_study2==1, 1, 0)

filtered$home_study<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_study)

### Gym Locations Vs Other Locations

filtered$gym4<-0
filtered$gym4<-ifelse(grepl("^6,",filtered$place), 1, filtered$gym4)
filtered$gym4<-ifelse(grepl(",6,",filtered$place),1, filtered$gym4)
filtered$gym4<-ifelse(grepl(",6$",filtered$place),1, filtered$gym4)
filtered$gym4<-ifelse(grepl("^6$",filtered$place),1, filtered$gym4)

filtered$home_gym<-filtered$gym4
filtered$home_gym<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_gym)

### Religious Locations Vs Other Locations

filtered$religion4<-0
filtered$religion4<-ifelse(grepl("^9,",filtered$place), 1, filtered$religion4)
filtered$religion4<-ifelse(grepl(",9,",filtered$place),1, filtered$religion4)
filtered$religion4<-ifelse(grepl(",9$",filtered$place),1, filtered$religion4)
filtered$religion4<-ifelse(grepl("^9$",filtered$place),1, filtered$religion4)

filtered$home_religion<-filtered$religion4
filtered$home_religion<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_religion)


### Social Locations Vs Other Locations

filtered$home_social4<-0
filtered$home_social4<-ifelse(grepl("^1,",filtered$place), 1, filtered$home_social4)
filtered$home_social4<-ifelse(grepl(",1,",filtered$place),1, filtered$home_social4)
filtered$home_social4<-ifelse(grepl(",1$",filtered$place),1, filtered$home_social4)
filtered$home_social4<-ifelse(grepl("^1$",filtered$place),1, filtered$home_social4)

filtered$home_social2<-0
filtered$home_social2<-ifelse(grepl("^2,",filtered$place), 1, filtered$home_social2)
filtered$home_social2<-ifelse(grepl(",2,",filtered$place),1, filtered$home_social2)
filtered$home_social2<-ifelse(grepl(",2$",filtered$place),1, filtered$home_social2)
filtered$home_social2<-ifelse(grepl("^2$",filtered$place),1,filtered$home_social2)
filtered$home_social3<-0
filtered$home_social3<-ifelse(grepl("^3,",filtered$place), 1, filtered$home_social3)
filtered$home_social3<-ifelse(grepl(",3,",filtered$place),1, filtered$home_social3)
filtered$home_social3<-ifelse(grepl(",3$",filtered$place),1, filtered$home_social3)
filtered$home_social3<-ifelse(grepl("^3$",filtered$place),1, filtered$home_social3)

filtered$home_social5<-0
filtered$home_social5<-ifelse(grepl("^5,",filtered$place), 1, filtered$home_social5)
filtered$home_social5<-ifelse(grepl(",5,",filtered$place),1, filtered$home_social5)
filtered$home_social5<-ifelse(grepl(",5$",filtered$place),1, filtered$home_social5)
filtered$home_social5<-ifelse(grepl("^5$",filtered$place),1, filtered$home_social5)

filtered$home_social<-ifelse(filtered$home_social4==1 | filtered$home_social2==1 | filtered$home_social3==1 |filtered$home_social5==1, 1, 0)

filtered$home_social<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_social)

i<-filtered %>%
  select(home_social, id, place)

inspect<-filtered %>%
  select(home_social, place, id)

filtered$home_social<-factor(filtered$home_social)
filtered$home_social<-relevel(filtered$home_social, ref="0")
levels(filtered$home_social)

filtered$home_nature<-ifelse(grepl("13", filtered$place), 1, 0)
filtered$home_nature<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_nature)

i<-filtered %>%
  select(home_nature, place, id )

filtered$home_nature<-factor(filtered$home_nature)
filtered$home_nature<-relevel(filtered$home_nature, ref="0")
levels(filtered$home_nature)

filtered$home_work<-ifelse(grepl("11", filtered$place), 1, 0)

filtered$home_work<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_work)

filtered$home_work<-factor(filtered$home_work)
filtered$home_work<-relevel(filtered$home_work, ref="0")
levels(filtered$home_work)

filtered$home_transit<-ifelse(grepl("12", filtered$place), 1, 0)
filtered$home_transit<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home_transit)


filtered$home_transit<-factor(filtered$home_transit)
filtered$home_transit<-relevel(filtered$home_transit, ref="0")
levels(filtered$home_transit)

filtered$home4<-0
filtered$home4<-ifelse(grepl("^7,",filtered$place), 1, filtered$home4)
filtered$home4<-ifelse(grepl(",7,",filtered$place),1, filtered$home4)
filtered$home4<-ifelse(grepl(",7$",filtered$place),1, filtered$home4)
filtered$home4<-ifelse(grepl("^7$",filtered$place),1, filtered$home4)

filtered$home<-filtered$home4
filtered$home<-ifelse(is.na(filtered$place),as.numeric(NA), filtered$home)

i<-filtered %>%
  select(home, id, place)

filtered$home<-factor(filtered$home)
filtered$home<-relevel(filtered$home, ref="0")


```

```{r}
### Aggregate Context Data by Week 

center_this <- function(x){
  (x - mean(x, na.rm=TRUE))
}

filtered<-filtered %>%
  dplyr::ungroup() %>%
  dplyr::group_by(id, week) %>%
  dplyr::mutate(
    socialLocation=mean(as.numeric(as.character(home_social)), na.rm=TRUE),
    natureLocation=mean(as.numeric(as.character(home_nature)), na.rm=TRUE),
    transitLocation=mean(as.numeric(as.character(home_transit)), na.rm=TRUE),
    workLocation=mean(as.numeric(as.character(home_work)), na.rm=TRUE),
    homeLocation=mean(as.numeric(as.character(home)), na.rm=TRUE),
    closeTiesPartner=mean(as.numeric(as.character(closeTies)), na.rm=TRUE),
    distantTiesPartner=mean(as.numeric(as.character(distantTies)), na.rm=TRUE),
    familyTiesPartner=mean(as.numeric(as.character(familyTies)), na.rm=TRUE),
    aloneTiesPartner=mean(as.numeric(as.character(alone)), na.rm=TRUE),
    gymLocation=mean(as.numeric(as.character(home_gym)), na.rm=TRUE),
    studyLocation=mean(as.numeric(as.character(home_study)), na.rm=TRUE),
    religionLocation=mean(as.numeric(as.character(home_religion)), na.rm=TRUE)
  ) %>%
  dplyr::distinct() %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
      angry_r=case_when(
      angry=="1" & !is.na(angry) ~ 4, 
      angry=="2" & !is.na(angry) ~ 3, 
      angry=="3" & !is.na(angry) ~ 2, 
      angry=="4" & !is.na(angry) ~ 1),
  worried_r=case_when(
     worried=="1" & !is.na(worried) ~ 4, 
     worried=="2" & !is.na(worried) ~ 3, 
     worried=="3" & !is.na(worried) ~ 2, 
     worried=="4" & !is.na(worried) ~ 1),
  sad_r=case_when(
    sad=="1" & !is.na(sad) ~ 4, 
    sad=="2" & !is.na(sad) ~ 3, 
    sad=="3" & !is.na(sad) ~ 2, 
    sad=="4" & !is.na(sad) ~ 1),
  stressed_r=case_when(
    stressed=="1" & !is.na(stressed) ~ 4, 
    stressed=="2" & !is.na(stressed) ~ 3, 
    stressed=="3" & !is.na(stressed) ~ 2, 
    stressed=="4" & !is.na(stressed) ~ 1),
  lonely_r=case_when(
    lonely=="1" & !is.na(lonely) ~ 4, 
    lonely=="2" & !is.na(lonely) ~ 3, 
    lonely=="3" & !is.na(lonely) ~ 2, 
    lonely=="4" & !is.na(lonely) ~ 1)
  )

select_vars<-filtered[,c("angry_r", "worried_r", "happy", "sad_r", "stressed_r", "lonely_r")]
filtered$wellbeing<-rowMeans(select_vars, na.rm = TRUE)

filtered$negative_affect <- apply(filtered[c("angry", "worried", "sad")], 1, function(x) {mean(x, na.rm = TRUE)})
filtered$affect_balance <- filtered$happy - filtered$negative_affect

#### Create Wellbeing Averages by Week 
filtered<-filtered %>%
  dplyr::ungroup() %>%
  dplyr::group_by(id, week) %>%
  dplyr::mutate(happy = mean(happy, na.rm = TRUE),
         angry = mean(angry_r, na.rm=TRUE), 
         worried = mean(worried_r, na.rm=TRUE),
         sad = mean(sad_r, na.rm=TRUE),
         lonely_r=mean(lonely_r, na.rm=TRUE),
         stressed_r=mean(stressed_r, na.rm=TRUE),
         accepted=mean(accepted, na.rm= TRUE),
         affect_balance=mean(affect_balance, na.rm=TRUE))%>%
  dplyr::select(id, week, angry, worried, sad, lonely_r, stressed_r, accepted, affect_balance, socialLocation, natureLocation, transitLocation, workLocation, homeLocation, gymLocation, religionLocation, studyLocation, closeTiesPartner, distantTiesPartner, familyTiesPartner) %>%
  dplyr::distinct() %>%
  dplyr::ungroup()

### Create Lagged Wellbeing Variables 
filtered<-filtered %>%
  dplyr::arrange(id, week) %>%
  dplyr::group_by(id) %>%
  dplyr::mutate(
    laggedAffectBalance=lag(affect_balance),
    laggedLonely=lag(lonely_r),
    laggedStress=lag(stressed_r),
    laggedAccepted=lag(accepted)
  )

filtered$familyGrandMean<-mean(filtered$familyTiesPartner, na.rm=TRUE)
filtered$closeTiesGrandMean<-mean(filtered$closeTiesPartner, na.rm=TRUE)
filtered$distantTiesGrandMean<-mean(filtered$distantTiesPartner, na.rm=TRUE)
filtered$transitGrandMean<-mean(filtered$transitLocation, na.rm=TRUE)
filtered$socialGrandMean<-mean(filtered$socialLocation, na.rm=TRUE)
filtered$natureGrandMean<-mean(filtered$natureLocation, na.rm=TRUE)
filtered$studyGrandMean<-mean(filtered$studyLocation, na.rm=TRUE)
filtered$religionGrandMean<-mean(filtered$religionLocation, na.rm=TRUE)
filtered$gymGrandMean<-mean(filtered$gymLocation, na.rm=TRUE)
filtered$workGrandMean<-mean(filtered$workLocation, na.rm=TRUE)

filtered$transitClusterMean<-ave(filtered$transitLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$socialClusterMean<-ave(filtered$socialLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$natureClusterMean<-ave(filtered$natureLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$closeTiesClusterMean<-ave(filtered$closeTiesPartner, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$distantTiesClusterMean<-ave(filtered$distantTiesPartner, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$familyTiesClusterMean<-ave(filtered$familyTiesPartner, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$studyClusterMean<-ave(filtered$studyLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$religionClusterMean<-ave(filtered$religionLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$gymClusterMean<-ave(filtered$gymLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))
filtered$workClusterMean<-ave(filtered$workLocation, filtered$id, FUN=function(x) mean(x, na.rm=T))


filtered$transitC<-filtered$transitLocation-filtered$transitClusterMean
filtered$socialC<-filtered$socialLocation-filtered$socialClusterMean
filtered$natureC<-filtered$natureLocation-filtered$natureClusterMean
filtered$closeTiesC<-filtered$closeTiesPartner-filtered$closeTiesClusterMean
filtered$distantTiesC<-filtered$distantTiesPartner-filtered$distantTiesClusterMean
filtered$familyTiesC<-filtered$familyTiesPartner-filtered$familyTiesClusterMean
filtered$studyC<-filtered$studyLocation-filtered$studyClusterMean
filtered$gymC<-filtered$gymLocation-filtered$gymClusterMean 
filtered$religionC<-filtered$religionLocation-filtered$religionClusterMean
filtered$workC<-filtered$workLocation-filtered$workClusterMean

filtered$transit.BP<-filtered$transitClusterMean-filtered$transitGrandMean
filtered$social.BP<-filtered$socialClusterMean-filtered$socialGrandMean
filtered$nature.BP<-filtered$natureClusterMean-filtered$natureGrandMean
filtered$closeTies.BP<-filtered$closeTiesClusterMean-filtered$closeTiesGrandMean
filtered$distantTies.BP<-filtered$distantTiesClusterMean-filtered$distantTiesGrandMean
filtered$familyTies.BP<-filtered$familyTiesClusterMean-filtered$familyGrandMean
filtered$study.BP<-filtered$studyClusterMean-filtered$studyGrandMean
filtered$gym.BP<-filtered$gymClusterMean-filtered$gymGrandMean
filtered$religion.BP<-filtered$religionClusterMean-filtered$religionGrandMean
filtered$work.BP<-filtered$workClusterMean-filtered$workLocation
```

```{r}
filtered$happy<-NULL
filtered$angry<-NULL
filtered$worried<-NULL
filtered$sad<-NULL

ema_weekly<-filtered %>%
  dplyr::select(id, week, transitC, socialC, natureC, closeTiesC, distantTiesC, familyTiesC, studyC, religionC, gymC,workC, affect_balance, lonely_r, stressed_r, accepted, week, transit.BP, social.BP, nature.BP, closeTies.BP, distantTies.BP, familyTies.BP, study.BP, religion.BP, gym.BP, work.BP, laggedAffectBalance, laggedLonely, laggedStress, laggedAccepted) %>%
  dplyr::rename(Week="week") %>%
  distinct()
```

### Preprocess Weekly App Usage Data 

```{r}
##### 1. Social Apps 
### Week 1 
select_vars<-data[,c("hours_social_w1", "minutes_social_w1")]
select_vars$minutes_social_w1<-select_vars$minutes_social_w1/60
data$social_Week1<-rowSums(select_vars, na.rm = TRUE)


### Week 2

select_vars<-data[,c("hours_social_w2", "minutes_social_w2")]
select_vars$minutes_social_w2<-select_vars$minutes_social_w2/60
data$social_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_social_w3", "minutes_social_w3")]
select_vars$minutes_social_w3<-select_vars$minutes_social_w3/60
data$social_Week3<-rowSums(select_vars, na.rm = TRUE)

### Week 4 

select_vars<-data[,c("hours_social_w4", "minutes_social_w4")]
select_vars$minutes_social_w4<-select_vars$minutes_social_w4/60
data$social_Week4<-rowSums(select_vars, na.rm = TRUE)


#### 2. Facebook 

### Week 1 

select_vars<-data[,c("hours_facebook_w1", "minutes_facebook_w1")]
select_vars$minutes_facebook_w1<-select_vars$minutes_facebook_w1/60
data$facebook_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_facebook_w2", "minutes_facebook_w2")]
select_vars$minutes_facebook_w2<-select_vars$minutes_facebook_w2/60
data$facebook_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_facebook_w3", "minutes_facebook_w3")]
select_vars$minutes_facebook_w3<-select_vars$minutes_facebook_w3/60
data$facebook_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_facebook_w4", "minutes_facebook_w4")]
select_vars$minutes_facebook_w4<-select_vars$minutes_facebook_w4/60
data$facebook_Week4<-rowSums(select_vars, na.rm = TRUE)

#### 3. Instagram 

### Week 1 

select_vars<-data[,c("hours_instagram_w1", "minutes_instagram_w1")]
select_vars$minutes_instagram_w1<-select_vars$minutes_instagram_w1/60
data$instagram_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_instagram_w2", "minutes_instagram_w2")]
select_vars$minutes_instagram_w2<-select_vars$minutes_instagram_w2/60
data$instagram_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_instagram_w3", "minutes_instagram_w3")]
select_vars$minutes_instagram_w3<-select_vars$minutes_instagram_w3/60
data$instagram_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_instagram_w4", "minutes_instagram_w4")]
select_vars$minutes_instagram_w4<-select_vars$minutes_instagram_w4/60
data$instagram_Week4<-rowSums(select_vars, na.rm = TRUE)

#### 4. Snapchat 

### Week 2

select_vars<-data[,c("hours_snapchat_w2", "minutes_snapchat_w2")]
select_vars$minutes_snapchat_w2<-select_vars$minutes_snapchat_w2/60
data$snapchat_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_snapchat_w3", "minutes_snapchat_w3")]
select_vars$minutes_snapchat_w3<-select_vars$minutes_snapchat_w3/60
data$snapchat_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_snapchat_w4", "minutes_snapchat_w4")]
select_vars$minutes_snapchat_w4<-select_vars$minutes_snapchat_w4/60
data$snapchat_Week4<-rowSums(select_vars, na.rm = TRUE)


#### 5. Twitter

### Week 1 

select_vars<-data[,c("hours_twitter_w1", "minutes_twitter_w1")]
select_vars$minutes_twitter_w1<-select_vars$minutes_twitter_w1/60
data$twitter_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_twitter_w2", "minutes_twitter_w2")]
select_vars$minutes_twitter_w2<-select_vars$minutes_twitter_w2/60
data$twitter_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_twitter_w3", "minutes_twitter_w3")]
select_vars$minutes_twitter_w3<-select_vars$minutes_twitter_w3/60
data$twitter_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_twitter_w4", "minutes_twitter_w4")]
select_vars$minutes_twitter_w4<-select_vars$minutes_twitter_w4/60
data$twitter_Week4<-rowSums(select_vars, na.rm = TRUE)

#### 6. Youtube

### Week 1 

select_vars<-data[,c("hours_youtube_w1", "minutes_youtube_w1")]
select_vars$minutes_youtube_w1<-select_vars$minutes_youtube_w1/60
data$youtube_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_youtube_w2", "minutes_youtube_w2")]
select_vars$minutes_youtube_w2<-select_vars$minutes_youtube_w2/60
data$youtube_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_youtube_w3", "minutes_youtube_w3")]
select_vars$minutes_youtube_w3<-select_vars$minutes_youtube_w3/60
data$youtube_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_youtube_w4", "minutes_youtube_w4")]
select_vars$minutes_youtube_w4<-select_vars$minutes_youtube_w4/60
data$youtube_Week4<-rowSums(select_vars, na.rm = TRUE)

#### 7. Reddit 

### Week 1 

select_vars<-data[,c("hours_reddit_w1", "minutes_reddit_w1")]
select_vars$minutes_reddit_w1<-select_vars$minutes_reddit_w1/60
data$reddit_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_reddit_w2", "minutes_reddit_w2")]
select_vars$minutes_reddit_w2<-select_vars$minutes_reddit_w2/60
data$reddit_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_reddit_w3", "minutes_reddit_w3")]
select_vars$minutes_reddit_w3<-select_vars$minutes_reddit_w3/60
data$reddit_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_reddit_w4", "minutes_reddit_w4")]
select_vars$minutes_reddit_w4<-select_vars$minutes_reddit_w4/60
data$reddit_Week4<-rowSums(select_vars, na.rm = TRUE)

#### 8. TikTok

#### tiktok 

### Week 1 

select_vars<-data[,c("hours_tiktok_w1", "minutes_tiktok_w1")]
select_vars$minutes_tiktok_w1<-select_vars$minutes_tiktok_w1/60
data$tiktok_Week1<-rowSums(select_vars, na.rm = TRUE)

### Week 2

select_vars<-data[,c("hours_tiktok_w2", "minutes_tiktok_w2")]
select_vars$minutes_tiktok_w2<-select_vars$minutes_tiktok_w2/60
data$tiktok_Week2<-rowSums(select_vars, na.rm = TRUE)


### Week 3 

select_vars<-data[,c("hours_tiktok_w3", "minutes_tiktok_w3")]
select_vars$minutes_tiktok_w3<-select_vars$minutes_tiktok_w3/60
data$tiktok_Week3<-rowSums(select_vars, na.rm = TRUE)


### Week 4 

select_vars<-data[,c("hours_tiktok_w4", "minutes_tiktok_w4")]
select_vars$minutes_tiktok_w4<-select_vars$minutes_tiktok_w4/60
data$tiktok_Week4<-rowSums(select_vars, na.rm = TRUE)


weekly<-data %>%
  dplyr::select(id, StartDate_w1, StartDate_w2, StartDate_w3, StartDate_w4,survey_day_w4,
                social_Week1, social_Week2, social_Week3, social_Week4,
                facebook_Week1, facebook_Week2, facebook_Week3, facebook_Week4,
                instagram_Week1, instagram_Week2, instagram_Week3, instagram_Week4, 
                snapchat_Week2, snapchat_Week3, snapchat_Week4,
                twitter_Week1, twitter_Week2, twitter_Week3, twitter_Week4,
                youtube_Week1, youtube_Week2, youtube_Week3, youtube_Week4,
                reddit_Week1, reddit_Week2, reddit_Week3, reddit_Week4,
                tiktok_Week1, tiktok_Week2, tiktok_Week3, tiktok_Week4)
```



### Prep Weekly App Usage data for Merging with EMA
```{r}
weekly1<-weekly %>%
  gather(use_time, hours, social_Week1:tiktok_Week4) %>%
  separate(use_time, c("Platform", "Week"), sep="_") %>%
  select(id, Platform, Week, hours) %>%
  distinct() %>%
  dplyr::ungroup() %>%
  dplyr::group_by(id, Platform) %>%
  dplyr::mutate(avgpptHours=mean(hours, na.rm=TRUE),
         hours.state=hours-avgpptHours) %>%
  dplyr::ungroup () %>%
  dplyr::group_by(Platform) %>%
  dplyr::mutate(sampleMeanHours=mean(hours),
                hours.trait=avgpptHours-sampleMeanHours) %>%
  dplyr::select(id, Platform, Week, hours.state, hours.trait) 


weekly1[weekly1== "Week1"] <- "Week 1"
weekly1[weekly1== "Week2"]<-"Week 2"
weekly1[weekly1=="Week3"]<-"Week 3"
weekly1[weekly1=="Week4"]<-"Week 4"
```



### Prep Individual Differences Data for Merging 

```{r}
sample_center_this <- function(x){
  (x - mean(x, na.rm=TRUE))
}


### Sample Mean Center Big Five Traits 
big5<-personality %>%
  dplyr::select(id, bfi_o, bfi_c, bfi_e, bfi_a, bfi_n) %>%
  dplyr::distinct() %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    bfi_o.c=sample_center_this(bfi_o),
    bfi_e.c=sample_center_this(bfi_e),
    bfi_n.c=sample_center_this(bfi_n),
    bfi_c.c=sample_center_this(bfi_c),
    bfi_a.c=sample_center_this(bfi_a)
  )

### Extract Sex and Age + Recode/Mean Center Them 
demog<-demogPers %>%
  select(pID, demog_sex, demog_age) %>%
  dplyr::distinct() %>%
  dplyr::rename(id="pID") %>%
  dplyr::mutate(demog_sex_recoded=dplyr::recode(demog_sex, `3`=3,`2`=1, `1`=0)) %>%
  dplyr::mutate(demog_sex_recoded=scale(demog_sex_recoded, center=TRUE, scale=FALSE),
                demog_age.c=scale(demog_age, center=TRUE, scale=FALSE))

### Extract Dispositional Wellbeing data From the Presurvey 
ps<-presurvey %>%
  dplyr::select(id, contains("swls_sum"), contains("awb"), contains("uls_mean"), contains("narqs_adm"), contains("narqs_riv"), contains("cesd"))

ps<-ps%>%
  dplyr::rename(AngryTrait=awb_1_t1,
                WorriedTrait=awb_2_t1,
                HappyTrait=awb_3_t1,
                SadTrait=awb_4_t1,
                EnthuTrait=awb_5_t1,
                RelaxedTrait=awb_6_t1) %>%
  distinct()

ps<-ps  %>%
  dplyr::mutate(
    angryTrait_r=case_when(
      AngryTrait=="1" & !is.na(AngryTrait) ~ 5, 
      AngryTrait=="2" & !is.na(AngryTrait) ~ 4, 
      AngryTrait=="3" & !is.na(AngryTrait) ~ 3, 
      AngryTrait=="4" & !is.na(AngryTrait) ~ 2,
      AngryTrait=="5" & !is.na(AngryTrait) ~ 1),
    worriedTrait_r=case_when(
      WorriedTrait=="1" & !is.na(WorriedTrait) ~ 5, 
      WorriedTrait=="2" & !is.na(WorriedTrait) ~ 4, 
      WorriedTrait=="3" & !is.na(WorriedTrait) ~ 3, 
      WorriedTrait=="4" & !is.na(WorriedTrait) ~ 2,
      WorriedTrait=="5" & !is.na(WorriedTrait) ~ 1),
    sadTrait_r=case_when(
      SadTrait=="1" & !is.na(SadTrait) ~ 5, 
      SadTrait=="2" & !is.na(SadTrait) ~ 4, 
      SadTrait=="3" & !is.na(SadTrait) ~ 3, 
      SadTrait=="4" & !is.na(SadTrait) ~ 2,
      SadTrait=="5" & !is.na(SadTrait) ~ 1))


select_vars<-ps[,c("angryTrait_r", "worriedTrait_r", "HappyTrait", "sadTrait_r", "EnthuTrait", "RelaxedTrait")]
ps$trait_wellbeing<-rowMeans(select_vars, na.rm = TRUE)

ps$negative_affect_trait <- apply(ps[c("AngryTrait", "WorriedTrait", "SadTrait")], 1, function(x) {mean(x, na.rm = TRUE)})
ps$affect_balance_trait <- ps$HappyTrait - ps$negative_affect_trait

ps<-ps %>%
  dplyr::mutate(
    trait_wellbeing.c=sample_center_this(trait_wellbeing),
    affect_balance_trait.c=sample_center_this(affect_balance_trait),
    uls_mean.c=sample_center_this(uls_mean),
    enthu_trait.c=sample_center_this(EnthuTrait),
    relaxed_trait.c=sample_center_this(RelaxedTrait),
    swls_sum.c=sample_center_this(swls_sum)
  ) %>%
  dplyr::select(id, trait_wellbeing.c, affect_balance_trait.c, uls_mean.c, enthu_trait.c, relaxed_trait.c, swls_sum.c) %>%
  distinct()

analysis_data<-ema_weekly %>%
  dplyr::ungroup() %>%
  dplyr::left_join(weekly1, by=c("id", "Week")) %>%
  dplyr::distinct() %>%
  dplyr::left_join(demog, by="id") %>%
  dplyr::distinct() %>%
  dplyr::left_join(big5, by="id") %>%
  dplyr::distinct() %>%
  dplyr::left_join(ps, by="id") %>%
  dplyr::distinct()

nPPts<-length(unique(analysis_data$id))
nObs<-length(analysis_data$id)

### Remove people over 25 and with sex coded as "3"

### 502 observations corresponding to 20 participants were filtered 

analysis_data<-analysis_data %>%
  dplyr::filter(demog_age<=25) %>%
  dplyr::filter(demog_sex!= 3)

nPPtsPostFilter<-length(unique(analysis_data$id))
nObsPostFilter<-length(analysis_data$id)

nPPTFiltered<-nPPts-nPPtsPostFilter
nOBSFiltered<-nObs-nObsPostFilter
```

```{r}
write.csv(analysis_data, "weekly_data.csv")
```


