---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(sjPlot)
library(jtools)
library(interactions)
setwd("~/Desktop/socialmediasensitivity/Social media Sensitivity Pooled Analyses/Pooled Analysis  - Dispositions/Lonely ")
main_effect_updated<-read_csv("modelling_data_pooled_updated.csv")
```

```{r}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,   demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample) %>%
  na.omit() %>% dplyr::distinct()

baseline_lonely_r_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                              demog_age.z+
                              surveys_per_id.z+
                              overall_study_day+
                              weekend+
                              nAct.cz+
                              lagDur.cz*laggedLonely.cz+
                              MediaUse.scaled+MediaUse.mean+ 
                              sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
                            REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))

mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample) %>%
  na.omit() %>% dplyr::distinct()

baseline_lonely_r_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                                    demog_age.z+
                                    surveys_per_id.z+
                                    overall_study_day+
                                    weekend+
                                    nAct.cz+
                                    lagDur.cz*laggedLonely.cz+
                                    socialmedia.cz+socialmedia.bp.z+
                                    sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                                  REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))

mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,  demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, affect_balance_trait.z) %>%
  na.omit() %>% dplyr::distinct()


trait_affectbalance_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                           demog_age.z+
                           surveys_per_id.z+
                           overall_study_day+
                           weekend+
                           nAct.cz+
                           lagDur.cz*laggedLonely.cz+
                           MediaUse.mean*affect_balance_trait.z+MediaUse.scaled*affect_balance_trait.z+
                           sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
                         REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(trait_affectbalance_sm)

int<-sim_slopes(trait_affectbalance_sm, pred=MediaUse.scaled, modx=affect_balance_trait.z, jnplot = TRUE)
plot<-interact_plot(trait_affectbalance_sm, pred=MediaUse.scaled, modx=affect_balance_trait.z, interval = TRUE) +xlab("Social Media Use (WP)") +ylab("Lonely")+theme_apa()+ggtitle("Affect Balance Trait")
plot
ggsave("Interact Affect Balance Moderator - Use.png")
jn_plot<-int$jnplot + xlab("Affect Balance Trait") +ylab ("Slope of SMU and Lonely")+theme_apa()+ggtitle("JN Plot")
jn_plot
ggsave("Affect Balance Moderator - Use - JN Plot.png")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="Positive Affect Balance", `- 1 SD`="Negative Affect Balance")
s<-ggplot(data=probe, aes(x=MediaUse.scaled, y=lonely_r, group=trial, colour=trial, fill=trial))+geom_line(size=1.5)+geom_ribbon(aes(ymin = ymin, ymax = ymax, group=trial, fill=trial), alpha=0.3)+xlab("Use vs Non-Use") + ylab("Loneliness") + coord_cartesian(
  ylim = c(3, 4),
  expand = TRUE,
  default = FALSE)+ scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Non-Use", "Use")) +
  theme_apa()+theme(axis.text = element_text(size = 30)) + scale_color_manual(values=c("#F98400", "#5BBCD6")) + scale_fill_manual(values=c("#F98400", "#5BBCD6"))+ theme(axis.text = element_text(size = 30), axis.title.x = element_text(size=30), axis.title.y=element_text(size=30), legend.text = element_text(size=30), legend.position = c(.999, .999), legend.justification = c("right", "top"),legend.box.just = "right", legend.margin = margin(6, 6, 6, 6))

ggsave("LinePlots: Trait Affect Balance Moderators (BP) of Social Media Use (WP) x Lonely.pdf", width=10, height=10)

probe2<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD") %>%
  dplyr::mutate(
    socialmedia=case_when(
    MediaUse.scaled<0 ~ "Before",
    MediaUse.scaled>0 ~ "After"
  ), context=case_when(
    modx_group=="+ 1 SD" ~ 
    "Positive
   Affect",
    modx_group== "- 1 SD" ~ 
    "Negative 
  Affect"
  )) %>%
  dplyr::group_by(context, socialmedia) %>%
  dplyr::summarise(
    wb=mean(lonely_r, na.rm=TRUE)) %>%
  arrange(desc(socialmedia))

probe2$socialmedia<-factor(probe2$socialmedia, levels=c("After", "Before"))
probe2$socialmedia<-fct_reorder(probe2$socialmedia, desc(probe2$socialmedia))

s<-ggplot(data=probe2, aes(x=context, y=wb, group=socialmedia, fill=socialmedia))+
  geom_col(width=0.5, position=position_dodge(), color="black")+theme_apa() + 
  scale_fill_manual(values=c('darkgrey','white')) + ylab(" ") + xlab(" ") + theme(axis.text = element_text(size = 20))  +  geom_errorbar(aes(ymin=wb-sd(wb, na.rm=TRUE), ymax=wb+sd(wb, na.rm=TRUE)), width=.2, position=position_dodge(.5)) + coord_cartesian(
    ylim = c(2.5,4),
    expand = TRUE,
    default = FALSE)
ggsave("Affect Balance Moderators (WP) - Bar Plot.pdf", height=8, width=8)



mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, affect_balance_trait.z) %>%
  na.omit() %>% dplyr::distinct()


trait_affectbalance_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                                 demog_age.z+
                                 surveys_per_id.z+
                                 overall_study_day+
                                 weekend+
                                 nAct.cz+
                                 lagDur.cz*laggedLonely.cz+
                                 socialmedia.bp.z*affect_balance_trait.z+socialmedia.cz*affect_balance_trait.z+
                                 sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                               REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(trait_affectbalance_duration)
```


```{r}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,   demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, socialConnectedness.z) %>%
  na.omit() %>% dplyr::distinct()


socialConnectedness_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                               demog_age.z+
                               surveys_per_id.z+
                               overall_study_day+
                               weekend+
                               nAct.cz+
                               lagDur.cz*laggedLonely.cz+
                               MediaUse.mean*socialConnectedness.z+MediaUse.scaled*socialConnectedness.z+
                               sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
                             REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(socialConnectedness_sm)

### Not including this because of the instrument
int<-sim_slopes(socialConnectedness_sm, pred=MediaUse.scaled, modx=socialConnectedness.z, jnplot = TRUE)
plot<-interact_plot(socialConnectedness_sm, pred=MediaUse.scaled, modx=socialConnectedness.z) +xlab("Social Media Use (WP)") +ylab("Lonely")+theme_apa()+ggtitle("Social Connectedness")
plot
ggsave("Social Connectedness Moderator - Use.png")
jn_plot<-int$jnplot + xlab("Social Connectedness") +ylab ("Slope of SMU and Lonely")+theme_apa()+ggtitle("JN Plot")
jn_plot
ggsave("Social Connectedness Moderator - Use - JN Plot.png") ### note to self: SC is reverse coded such that higher values indicate greater loneliness

mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, socialConnectedness.z) %>%
  na.omit() %>% dplyr::distinct()

socialConnectedness_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                                     demog_age.z+
                                     surveys_per_id.z+
                                     overall_study_day+
                                     weekend+
                                     nAct.cz+
                                     lagDur.cz*laggedLonely.cz+
                                     socialmedia.bp.z*socialConnectedness.z+socialmedia.cz*socialConnectedness.z+
                                     sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                                   REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(socialConnectedness_duration)
```

```{r}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,   demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, cesd.z) %>%
  na.omit() %>% dplyr::distinct()


cesd_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                demog_age.z+
                surveys_per_id.z+
                overall_study_day+
                weekend+
                nAct.cz+
                lagDur.cz*laggedLonely.cz+
                MediaUse.mean*cesd.z+MediaUse.scaled*cesd.z+
                sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
              REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(cesd_sm)


int<-sim_slopes(cesd_sm, pred=MediaUse.scaled, modx=cesd.z, jnplot = TRUE)
plot<-interact_plot(cesd_sm, pred=MediaUse.scaled, modx=cesd.z, interval=TRUE) +xlab("Social Media Use (WP)") +ylab("Lonely")+theme_apa()+ggtitle("CESD")
plot
ggsave("CESD Moderator - Use.png")
jn_plot<-int$jnplot + xlab("CESD") +ylab ("Slope of SMU and Lonely")+theme_apa()+ggtitle("JN Plot")
jn_plot
ggsave("CESD Moderator - Use - JN Plot.png")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="High Depression", `- 1 SD`="Low Depression")
s<-ggplot(data=probe, aes(x=MediaUse.scaled, y=lonely_r, group=trial, colour=trial, fill=trial))+geom_line(size=1.5)+geom_ribbon(aes(ymin = ymin, ymax = ymax, group=trial, fill=trial), alpha=0.3)+xlab("Use vs Non-Use") + ylab("Loneliness") + coord_cartesian(
  ylim = c(3, 4),
  expand = TRUE,
  default = FALSE)+ scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Non-Use", "Use")) +
  theme_apa()+theme(axis.text = element_text(size = 30)) + scale_color_manual(values=c("#F98400", "#5BBCD6")) + scale_fill_manual(values=c("#F98400", "#5BBCD6"))+ theme(axis.text = element_text(size = 30), axis.title.x = element_text(size=30), axis.title.y=element_text(size=30), legend.text = element_text(size=30), legend.position = c(.999, .999), legend.justification = c("right", "top"),legend.box.just = "right", legend.margin = margin(6, 6, 6, 6))

ggsave("Lineplot: Depression Moderators (BP) of Social Media Use (WP) x Lonely.pdf", width=10, height=10)

probe2<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD") %>%
  dplyr::mutate(
    socialmedia=case_when(
    MediaUse.scaled<0 ~ "Before",
    MediaUse.scaled>0 ~ "After"
  ), context=case_when(
    modx_group=="+ 1 SD" ~ "High 
  Depression",
    modx_group== "- 1 SD" ~ "Low
  Depression"
  )) %>%
  dplyr::group_by(context, socialmedia) %>%
  dplyr::summarise(
    wb=mean(lonely_r, na.rm=TRUE)) %>%
  arrange(desc(socialmedia))

probe2$socialmedia<-factor(probe2$socialmedia, levels=c("After", "Before"))
probe2$socialmedia<-fct_reorder(probe2$socialmedia, desc(probe2$socialmedia))

s<-ggplot(data=probe2, aes(x=context, y=wb, group=socialmedia, fill=socialmedia))+
  geom_col(width=0.5, position=position_dodge(), color="black")+theme_apa() + 
  scale_fill_manual(values=c('darkgrey','white')) + ylab(" ") + xlab(" ") + theme(axis.text = element_text(size = 20))  +  geom_errorbar(aes(ymin=wb-sd(wb, na.rm=TRUE), ymax=wb+sd(wb, na.rm=TRUE)), width=.2, position=position_dodge(.5)) + coord_cartesian(
    ylim = c(2.5,4),
    expand = TRUE,
    default = FALSE)
ggsave("Depression Moderators (WP) - Bar Plot.pdf", height=8, width=8)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, cesd.z) %>%
  na.omit() %>% dplyr::distinct()


cesd_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                      demog_age.z+
                      surveys_per_id.z+
                      overall_study_day+
                      weekend+
                      nAct.cz+
                      lagDur.cz*laggedLonely.cz+
                      socialmedia.bp.z*cesd.z+socialmedia.cz*cesd.z+
                      sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                    REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(cesd_duration)
```

```{r}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,   demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, swls_sum.z) %>%
  na.omit() %>% dplyr::distinct()



swls_sum_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                    demog_age.z+
                    surveys_per_id.z+
                    overall_study_day+
                    weekend+
                    nAct.cz+
                    lagDur.cz*laggedLonely.cz+
                    MediaUse.mean*swls_sum.z+MediaUse.scaled*swls_sum.z+
                    sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
                  REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(swls_sum_sm)

plot<-interact_plot(swls_sum_sm, pred=MediaUse.scaled, modx=swls_sum.z, interval=TRUE) +xlab("Social Media Use (WP)") +ylab("Lonely")+theme_apa()+ggtitle("SWLS")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="High Satisfaction with Life", `- 1 SD`="Low Satisfaction with Life")

s<-ggplot(data=probe, aes(x=MediaUse.scaled, y=lonely_r, group=trial, colour=trial, fill=trial))+geom_line(size=1.5)+geom_ribbon(aes(ymin = ymin, ymax = ymax, group=trial, fill=trial), alpha=0.3)+xlab("Use vs Non-Use") + ylab("Loneliness") + coord_cartesian(
  ylim = c(3, 4),
  expand = TRUE,
  default = FALSE)+ scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Non-Use", "Use")) +
  theme_apa()+theme(axis.text = element_text(size = 30)) + scale_color_manual(values=c("#F98400", "#5BBCD6")) + scale_fill_manual(values=c("#F98400", "#5BBCD6"))+ theme(axis.text = element_text(size = 30), axis.title.x = element_text(size=30), axis.title.y=element_text(size=30), legend.text = element_text(size=30), legend.position = c(.98, .98), legend.justification = c("right", "top"),legend.box.just = "right", legend.margin = margin(6, 6, 6, 6))

ggsave("LinePlot: SWLS Moderators (WP) - Bar Plot.pdf", height=10, width=10)


probe2<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD") %>%
  dplyr::mutate(
    socialmedia=case_when(
    MediaUse.scaled<0 ~ "Before",
    MediaUse.scaled>0 ~ "After"
  ), context=case_when(
    modx_group=="+ 1 SD" ~ "High SWLS",
    modx_group== "- 1 SD" ~ "Low SWLS"
  )) %>%
  dplyr::group_by(context, socialmedia) %>%
  dplyr::summarise(
    wb=mean(lonely_r, na.rm=TRUE)) %>%
  arrange(desc(socialmedia))

probe2$socialmedia<-factor(probe2$socialmedia, levels=c("After", "Before"))
probe2$socialmedia<-fct_reorder(probe2$socialmedia, desc(probe2$socialmedia))
probe2$context<-factor(probe2$context, levels=c("High SWLS", "Low SWLS"))
probe2$context<-fct_reorder(probe2$context, desc(probe2$context))


mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, swls_sum.z) %>%
  na.omit() %>% dplyr::distinct()


swls_sum_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                          demog_age.z+
                          surveys_per_id.z+
                          overall_study_day+
                          weekend+
                          nAct.cz+
                          lagDur.cz*laggedLonely.cz+
                          socialmedia.bp.z*swls_sum.z+socialmedia.cz*swls_sum.z+
                          sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                        REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(swls_sum_duration)
```

```{r}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, MediaUse.scaled, MediaUse.mean,   demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, uls_mean.z) %>%
  na.omit() %>% dplyr::distinct()


uls_mean_sm<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                    demog_age.z+
                    surveys_per_id.z+
                    overall_study_day+
                    weekend+
                    nAct.cz+
                    lagDur.cz*laggedLonely.cz+
                    MediaUse.mean*uls_mean.z+MediaUse.scaled*uls_mean.z+
                    sample+(1+MediaUse.scaled| id),  na.action = na.exclude, data=mainEffect,
                  REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(uls_mean_sm)

int<-sim_slopes(uls_mean_sm, pred=MediaUse.scaled, modx=uls_mean.z, jnplot = TRUE)
plot<-interact_plot(uls_mean_sm, pred=MediaUse.scaled, modx=uls_mean.z) +xlab("Social Media Use Duration (WP)") +ylab("Lonely")+theme_apa()+ggtitle("Loneliness")
plot
ggsave("Interact: Loneliness Moderator - Use.png")
jn_plot<-int$jnplot + xlab("Loneliness") +ylab ("Slope of SMU and Lonely")+theme_apa()+ggtitle("JN Plot")
jn_plot
ggsave("Loneliness Moderator - Use - JN Plot.png")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="High Loneliness Trait", `- 1 SD`="Low Loneliness Trait")
s<-ggplot(data=probe, aes(x=MediaUse.scaled, y=lonely_r, group=trial, colour=trial, linetype=trial))+geom_line(size=1.5)+theme_apa() + scale_color_manual(values=c('Grey','Black')) +xlab("Social Media Use (vs Non-Use) (WP)") + ylab("Lonely (R)") + ylim(1,4) + scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Before", "After")) + theme_apa()+theme(axis.text = element_text(size = 15))

ggsave("Loneliness Moderators (BP) of Social Media Use (WP) x Lonely.pdf", width=8, height=8)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, StartDateConvert, lonely_r, demog_age.z, socialmedia.cz, socialmedia.bp.z, demog_sex_recoded, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, laggedLonely.cz, overall_study_day, sample, uls_mean.z) %>%
  na.omit() %>% dplyr::distinct()


uls_mean_duration<-lmer(lonely_r ~ 1 + demog_sex_recoded+    
                          demog_age.z+
                          surveys_per_id.z+
                          overall_study_day+
                          weekend+
                          nAct.cz+
                          lagDur.cz*laggedLonely.cz+
                          socialmedia.bp.z*uls_mean.z+socialmedia.cz*uls_mean.z+
                          sample+(1+socialmedia.cz| id),  na.action = na.exclude, data=mainEffect,
                        REML = TRUE, control = lmerControl(optimizer ="Nelder_Mead"))
summary(uls_mean_duration)

int<-sim_slopes(uls_mean_duration, pred=socialmedia.bp.z, modx=uls_mean.z, jnplot = TRUE)
plot<-interact_plot(uls_mean_duration, pred=socialmedia.bp.z, modx=uls_mean.z) +xlab("Social Media Use Duration (BP)") +ylab("Lonely")+theme_apa()+ggtitle("Loneliness")
plot
ggsave("Interact: Loneliness Moderator - Duration (BP).png")
jn_plot<-int$jnplot + xlab("Loneliness") +ylab ("Slope of SMU Duration (BP) and Lonely")+theme_apa()+ggtitle("JN Plot")
jn_plot
ggsave("Loneliness Moderator - Duration (BP) - JN Plot.png")

probe<-plot$data %>%
  dplyr::filter(modx_group=="+ 1 SD" | modx_group=="- 1 SD")

probe$trial<-recode_factor(probe$modx_group, `+ 1 SD`="High Loneliness Trait", `- 1 SD`="Low Loneliness Trait")
s<-ggplot(data=probe, aes(x=socialmedia.bp.z, y=lonely_r, group=trial, colour=trial, linetype=trial))+geom_line(size=1.5)+theme_apa() + scale_color_manual(values=c('Grey','Black')) +xlab("Social Media Use (vs Non-Use) (WP)") + ylab("Lonely (R)") + ylim(1,4) + scale_x_continuous(breaks=seq(-1,1, 2),labels=c("Before", "After")) + theme_apa()+theme(axis.text = element_text(size = 15))

ggsave("Loneliness Moderators (BP) of Social Media Duration (BP) x Lonely.pdf", width=8, height=8)
```

### Table Module 

```{r}
predLabels=c("Intercept",
             "Sex", 
             "Age",
             "Surveys Per Participant",
             "Study Day", 
             "Weekend", 
             "Number of Activites", 
             "Duration Since Last EMA", 
             "Wellbeing at t-1", 
             "Social Media Use Duration (WP)",
             "Social Media Use Duration (BP)",
             "Duration Since Last EMA x Wellbeing at t-1",
             "Trait Affect Balance", 
             "Social Media Use Duration (BP) x Affect Balance Trait (BP)", 
             "Social Media Use Duration (WP) x Affect Balance Trait (BP)", 
             "Depression",
             "Social Media Use Duration (BP) x Depression (BP)",
             "Social Media Use Duration (WP) x Depression (BP)",
             "Social Connectedness", 
             "Social Media Use Duration (BP) x Social Connectedness (BP)",
             "Social Media Use Duration (WP) x Social Connectedness (BP)", 
             "Satisfaction With Life", 
             "Social Media Use Duration (BP) x Satisfaction with Life (BP)",
             "Social Media Use Duration (WP) x Satisfaction with Life (BP)",
             "Loneliness",
             "Social Media Use Duration (BP) x Loneliness (BP)",
             "Social Media Use Duration (WP) x Loneliness (BP)")

dvLabels=c("Baseline Model",
           "Trait Wellbeing Moderator",
           "Depression Moderator",
           "Social Connectedness Moderator",
           "Satisfaction with Life Moderator",
           "Loneliness Moderator")

tab_model(baseline_lonely_r_duration, 
          trait_lonely_r_duration,
          cesd_duration,
          socialConnectedness_duration, 
          swls_sum_duration, 
          uls_mean_duration,
          pred.labels = predLabels,
          dv.labels = dvLabels,
          file="Duration_WellbeingModerators_lonely_r.html")


predLabels=c("Intercept",
             "Sex", 
             "Age",
             "Surveys Per Participant",
             "Study Day", 
             "Weekend", 
             "Number of Activites", 
             "Duration Since Last EMA", 
             "Wellbeing at t-1", 
             "Social Media Use (vs Non-Use) (WP)",
             "Social Media Use (vs Non-Use) (BP)",
             "Duration Since Last EMA x Wellbeing at t-1",
             "Trait Affect Balance", 
             "Social Media Use (vs Non-Use) (BP) x Affect Balance Trait (BP)", 
             "Social Media Use (vs Non-Use) (WP) x Affect Balance Trait (BP)", 
             "Depression",
             "Social Media Use (vs Non-Use) (BP) x Depression (BP)",
             "Social Media Use (vs Non-Use) (WP) x Depression (BP)",
             "Social Connectedness", 
             "Social Media Use (vs Non-Use) (BP) x Social Connectedness (BP)",
             "Social Media Use (vs Non-Use) (WP) x Social Connectedness (BP)", 
             "Satisfaction With Life", 
             "Social Media Use (vs Non-Use) (BP) x Satisfaction with Life (BP)",
             "Social Media Use (vs Non-Use) (WP) x Satisfaction with Life (BP)",
             "Loneliness",
             "Social Media Use (vs Non-Use) (BP) x Loneliness (BP)",
             "Social Media Use (vs Non-Use) (WP) x Loneliness (BP)")

dvLabels=c("Baseline Model",
           "Trait Wellbeing Moderator",
           "Depression Moderator",
           "Social Connectedness Moderator",
           "Satisfaction with Life Moderator",
           "Loneliness Moderator")

tab_model(baseline_lonely_r_sm, 
          trait_lonely_r_sm,
          cesd_sm,
          socialConnectedness_sm, 
          swls_sum_sm, 
          uls_mean_sm,
          pred.labels = predLabels,
          dv.labels = dvLabels,
          file="UseVsNoUse_WellbeingModerator_lonely_r.html")
```